return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.0",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 34,
  height = 12,
  tilewidth = 40,
  tileheight = 40,
  nextlayerid = 5,
  nextobjectid = 1,
  backgroundcolor = { 255, 255, 255 },
  properties = {},
  tilesets = {},
  layers = {
    {
      type = "imagelayer",
      image = "../../../assets/sprites/back_mountains.png",
      id = 2,
      name = "back_mountains",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 642.333,
      offsety = 89.6667,
      parallaxx = 0.9,
      parallaxy = 1,
      repeatx = true,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/back_mountains.png",
      id = 3,
      name = "back_back_mountains",
      class = "",
      visible = true,
      opacity = 0.7,
      offsetx = 586.333,
      offsety = 86.6667,
      parallaxx = 1.3,
      parallaxy = 1,
      tintcolor = { 255, 85, 255 },
      repeatx = true,
      repeaty = false,
      properties = {}
    },
    {
      type = "imagelayer",
      image = "../../../assets/sprites/delta_rune.png",
      id = 4,
      name = "delta rune",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 941.333,
      offsety = 16.6667,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
