return {
	no_trance=function(cutscene)
		Kristal.callEvent("completeAchievement", "spare")
		local susie = cutscene:getCharacter("susie")
		local noelle = cutscene:getCharacter("noelle")
		susie:setSprite("walk")
		cutscene:look(susie, "right")
		noelle:setSprite("walk")
		cutscene:look(noelle, "left")
		cutscene:wait(0.75)

		cutscene:text("* Wow.[wait:1] What the hell is that thing you were wearing?", "nervous", "susie")
		cutscene:text("* It doesn't even looks like a ring,[wait:1] it's just...", "smirk", "susie")
		cutscene:text("* ...[wait:1]Thorns.", "neutral_side", "susie")
		cutscene:text("* It's...", "sad_smile", "noelle")
		cutscene:text("* (...)", "down", "noelle")
		cutscene:text("* (I can't tell Susie it was Kris...)", "down_smile", "noelle")
		cutscene:text("* (What if she grab them and throw them on the ground...)", "sad_side", "noelle")
		cutscene:text("* (And then beat them up...)", "sad", "noelle")
		cutscene:text("* (Would Susie even do that for me?)", "sad_smile_b", "noelle")
		cutscene:text("* Um...[wait:1] Noelle, you're good?", "sus_nervous", "susie")
		cutscene:text("* U-[wait:1]Uh??", "confused_surprise", "noelle")
		cutscene:text("* You looked at me for a while without saying anything.", "sus_nervous", "susie")
		cutscene:text("* You don't wear another one of those weird things, right?", "nervous_side", "susie")
		cutscene:text("* N-[wait:1]No no![wait:1] Sorry,[wait:1] I was just...", "surprise_smile", "noelle")
		cutscene:text("* Lost in my thoughts.", "sad_smile_b", "noelle")
		cutscene:text("* Hm.", "neutral_side", "susie")
		cutscene:text("* I guess after that,[wait:1] you don't really wanna wake up, do you?", "annoyed_down", "susie")
		cutscene:text("* U-[wait:1]Uh?[wait:1] I mean...", "blush", "noelle")
		cutscene:text("* (Maybe this nightmare is finally over...)", "smile_side", "noelle")
		cutscene:text("* Ma-[wait:1]Maybe I can spend a little while...[wait:1] with...", "smile_closed", "noelle")
		cutscene:text("* You?", "blush_finger", "noelle")
		cutscene:text("* Heh,[wait:1] sure.", "smirk", "susie")
		cutscene:text("* Really??", "blush_big_smile", "noelle")
		cutscene:text("* Yeah.", "smirk", "susie")
		cutscene:text("* I was just about to go check up on Ralsei and Kris.", "smile", "susie")
		cutscene:text("* You can come with me.", "smile", "susie")
		cutscene:text("* Ah uh...[wait:1] Well...", "blush_surprise", "noelle")
		cutscene:text("* Sure.[wait:1] I'll come along!", "blush_smile", "noelle")
		cutscene:text("* Nice,[wait:1] let's go then!", "sincere_smile", "susie")
		Assets.playSound("charjoined")
		cutscene:text("[voice:default]* Noelle has joined the party!")

		noelle.actor.default = "walk_blush"
		noelle:setSprite("walk_blush")
		noelle:convertToFollower()
		Game:addPartyMember("noelle")
		cutscene:alignFollowers()
		cutscene:attachFollowers()
		cutscene:wait(cutscene:attachCamera(1))
		Game.inventory:addItem("thornring")
		Game:setFlag("plot", 3)
		Game:saveQuick()
	end,
	thorn_kill=function(cutscene)
		Kristal.callEvent("completeAchievement", "thorn")
		local susie = cutscene:getCharacter("susie")
		local noelle = cutscene:getCharacter("noelle")
		susie:setSprite("walk")
		cutscene:look(susie, "right")
		noelle:setSprite("battle/defeat")
		cutscene:wait(0.5)

		cutscene:text("* ...", "surprise_frown", "susie")
		cutscene:setAnimation(susie, {"away_scratch", 1/6, true})
		cutscene:text("* So,[wait:0.5] uh...", "neutral_side", "susie")
		cutscene:text("* Are you finished...?", "nervous_side", "susie")
		cutscene:text("* [speed:0.6]...Why...?", "trance", "noelle")
		cutscene:text("* Well...[wait:1] uh...", "nervous_side", "susie")
		cutscene:setSprite(susie, "walk")
		cutscene:text("* Hey,[wait:0.5] wait a sec!!", "surprise", "susie")
		cutscene:text("* You're the one who attacked me first.", "nervous", "susie")
		cutscene:text("* So I should be the one to ask!", "teeth", "susie")
		cutscene:text("* WHY?!", "teeth_b", "susie")
		cutscene:wait(1.5)
		cutscene:text("* ...", "trance", "noelle")
		Assets.playSound("noise")
		cutscene:setSprite(noelle, "walk_kill")
		cutscene:look(noelle, "right")
		cutscene:wait(0.5)
		cutscene:text("* ...?", "shock", "susie")
		cutscene:text("* They are calling.", "trance", "noelle")
		cutscene:text("* Calling...?[wait:1] Wh-", "shock", "susie")
		cutscene:walkTo(noelle, noelle.x+320, noelle.y, 9)
		local waitFade=false
		Game.world.fader:fadeOut(function() waitFade=true end, {speed=8})
		susie:shake(3)
		susie:setSprite("exasperated_right")
		cutscene:text("* Hey![wait:1] Noelle,[wait:0.5] where are you going?![wait:0.7]", "surprise_frown", "susie", {auto=true, advance=false, wait=true, skip=false})
		susie:shake(4)
		cutscene:text("* You almost got almost stung to death and you just walk away??[wait:0.5]", "shy_b", "susie", {auto=true, advance=false, wait=true, skip=false})
		susie:shake(5)
		cutscene:text("* Noelle![wait:1] Answer,[wait:0.5] damnit![wait:0.6]", "angry", "susie", {auto=true, advance=false, wait=true, skip=false})
		susie:shake(6)
		cutscene:text("* Stop trying to go away!![wait:0.7]", "angry_b", "susie", {auto=true, advance=false, wait=true, skip=false})
		susie:shake(7)
		cutscene:text("* This isn't even the exit!![wait:0.7]", "teeth_b", "susie", {auto=true, advance=false, wait=true, skip=false})
		susie:shake(10)
		cutscene:text("* IT'S A FREAKING HEART-SHAPED FERRIS WHEEL!!![wait:0.1]", "teeth", "susie", {auto=true, advance=false, wait=true, skip=false})
		cutscene:wait(function()
			return waitFade
		end)
		cutscene:wait(1)
		Game:setFlag("plot", 3)
		cutscene:gotoCutscene("ending.killing_spamton")
	end,
	killspare=function(cutscene)
		Kristal.callEvent("completeAchievement", "violentspare")
		local susie = cutscene:getCharacter("susie")
		local noelle = cutscene:getCharacter("noelle")
		susie:setSprite("walk")
		cutscene:look(susie, "right")
		noelle:setSprite("battle/defeat")
		cutscene:wait(0.5)

		cutscene:text("* Noelle!", "surprise_frown", "susie")
		cutscene:text("* Can you hear me??", "sad_frown", "susie")
		cutscene:text("* [speed:0.6]...", "dejected", "noelle")
		cutscene:text("* [speed:0.4]...[wait:1]It hurts...", "sad", "noelle")
		noelle.actor.flip="left"
		noelle:setSprite("collapsed")
		Assets.playSound("noise")
		cutscene:text("* Noelle!", "surprise_frown", "susie")
		susie.actor.flip="right"
		cutscene:setAnimation(susie, {"heal", 1/16})
		cutscene:wait(function()
			return susie.sprite.frame>=11
		end)
		Assets.playSound("snd_spellcast")
		local heal_bullet = Sprite('party/susie/dark/heal_small', susie.x+susie.width, (susie.y-susie.height/2)-24)
		heal_bullet.layer=susie.layer+1
		heal_bullet:setScale(2)
		Game.world:addChild(heal_bullet)
		heal_bullet:play(1/12, false)
		Game.world.timer:tween(2, heal_bullet, {x=noelle.x-noelle.width*2})
		cutscene:wait(2)
		heal_bullet:remove()
		local offset = noelle.sprite:getOffset()
		local flash = FlashFade(noelle.sprite.texture, offset[1], offset[2])
		flash.layer = 100
		noelle:addChild(flash)
		Assets.playSound("snd_spell_cure_slight_smaller")
		cutscene:wait(0.45)
		local sus_layer=susie.layer
		susie.layer=0.3
		susie.actor.flip="left"
		susie:setSprite("walk")
		cutscene:wait(cutscene:walkTo(susie, noelle.x+noelle.width/2, noelle.y))
		cutscene:setSprite(susie, "landed")
		cutscene:wait(0.5)
		cutscene:text("* .[wait:1].[wait:1].[wait:1]", "bangs_neutral", "susie")
		cutscene:text("* She's still breathing...[wait:1] Good.", "bangs_neutral", "susie")
		susie:setSprite("walk")
		cutscene:look(susie, "down")
		cutscene:wait(0.75)
		cutscene:text("* ...[wait:1]What do I even do now?", "nervous", "susie")
		cutscene:wait(1)
		cutscene:wait(cutscene:walkTo(susie, 640, 287, 1, "up"))
		cutscene:wait(0.75)
		cutscene:look(susie, "right")
		cutscene:wait(0.5)
		cutscene:text("* ...", "neutral_side", "susie")
		cutscene:walkTo(susie, noelle.x+noelle.width/2, noelle.y, 1.5)
		cutscene:fadeOut(0.5)
		cutscene:wait(1)
		Assets.playSound("noise")
		cutscene:wait(1.5)
		Assets.playSound("snd_heavyswing_bc")
		susie.layer=sus_layer
		susie:setPosition(640, 287)
		cutscene:look(susie, "up")
		local noelle_head=Sprite("Noelle_sleeping_in_bed", 560, 185)
		noelle_head:setScale(2)
		noelle_head.layer=0.3
		Game.world:addChild(noelle_head)
		Game.world:getEvent(26):remove()
		cutscene:wait(0.25)
		cutscene.textbox_actor=nil
		cutscene:text("* (Susie took Noelle's ThornRing.)", nil, nil)
		cutscene:fadeIn(0.5)
		cutscene:wait(1)
		cutscene:text("* ...", "neutral_side", "susie")
		cutscene:text("* I better go check on Kris and Ralsei now.", "neutral", "susie")
		cutscene:look(susie, "left")
		cutscene:attachCamera(0.5)
		cutscene:wait(0.5)
		Game.inventory:addItem("thornring")
		Game:setFlag("plot", 3)
		Game:saveQuick()
	end,
	killkill=function(cutscene)
		Kristal.callEvent("completeAchievement", "violence")
		cutscene:wait(cutscene:fadeOut(0))
		Game:setFlag("plot", 3)
		cutscene:gotoCutscene("ending.killing_spamton")
	end,

	iceshock=function(cutscene)
		Game:setFlag("plot", 3)
		cutscene:wait(cutscene:fadeOut(0))
		cutscene:wait(cutscene:mapTransition("fountain_room"))
		cutscene:gotoCutscene("ending.closing_fountain")
	end,
	snowgrave=function(cutscene)
		cutscene:wait(cutscene:fadeOut(0))
		cutscene:wait(cutscene:mapTransition("fountain_room"))
		cutscene:gotoCutscene("ending.closing_fountain")
	end
}