return {
	no_trance=function(cutscene)
		local susie = cutscene:getCharacter("susie")
		local noelle = cutscene:getCharacter("noelle")
		susie:setSprite("walk")
		cutscene:look(susie, "right")
		noelle:setSprite("walk")
		cutscene:look(noelle, "left")
		cutscene:wait(0.75)

		cutscene:text("* Wow.[wait:1] What the hell is that thing you were wearing?", "nervous", "susie")
		cutscene:text("* It doesn't even looks like a ring,[wait:1] it's just...", "smirk", "susie")
		cutscene:text("* ...[wait:1]Thorns.", "neutral_side", "susie")
		cutscene:text("* It's...", "sad_smile", "noelle")
		cutscene:text("* (...)", "down", "noelle")
		cutscene:text("* (I can't tell Susie it was Kris...)", "down_smile", "noelle")
		cutscene:text("* (What if she grab them and throw them on the ground...)", "sad_side", "noelle")
		cutscene:text("* (And then beat them up...)", "sad", "noelle")
		cutscene:text("* (Would Susie even do that for me?)", "sad_smile_b", "noelle")
		cutscene:text("* Um...[wait:1] Noelle, you're good?", "sus_nervous", "susie")
		cutscene:text("* U-[wait:1]Uh??", "confused_surprise", "noelle")
		cutscene:text("* You looked at me for a while without saying anything.", "sus_nervous", "susie")
		cutscene:text("* You don't wear another one of those weird things, right?", "nervous_side", "susie")
		cutscene:text("* N-[wait:1]No no![wait:1] Sorry,[wait:1] I was just...", "surprise_smile", "noelle")
		cutscene:text("* Lost in my thoughts.", "sad_smile_b", "noelle")
		cutscene:text("* Hm.", "neutral_side", "susie")
		cutscene:text("* I guess after that,[wait:1] you don't really wanna wake up, do you?", "annoyed_down", "susie")
		cutscene:text("* U-[wait:1]Uh?[wait:1] I mean...", "blush", "noelle")
		cutscene:text("* (Maybe this nightmare is finally over...)", "smile_side", "noelle")
		cutscene:text("* Ma-[wait:1]Maybe I can spend a little while...[wait:1] with...", "smile_closed", "noelle")
		cutscene:text("* You?", "blush_finger", "noelle")
		cutscene:text("* Heh,[wait:1] sure.", "smirk", "susie")
		cutscene:text("* Really??", "blush_big_smile", "noelle")
		cutscene:text("* Yeah.", "smirk", "susie")
		cutscene:text("* I was just about to go check up on Ralsei and Kris.", "smile", "susie")
		cutscene:text("* You can come with me.", "smile", "susie")
		cutscene:text("* Ah uh...[wait:1] Well...", "blush_surprise", "noelle")
		cutscene:text("* Sure.[wait:1] I'll come along!", "blush_smile", "noelle")
		cutscene:text("* Nice,[wait:1] let's go then!", "sincere_smile", "susie")
		Assets.playSound("charjoined")
		cutscene:text("* Noelle has joined the party!")

		noelle:setSprite("walk_blush")
		noelle:convertToFollower()
		Game:addPartyMember("noelle")
		cutscene:attachFollowers(0.25)
		cutscene:wait(cutscene:attachCamera(1))
	end,
	thorn_kill=function(cutscene)
		local susie = cutscene:getCharacter("susie")
		local noelle = cutscene:getCharacter("noelle")
		susie:setSprite("walk")
		cutscene:look(susie, "right")
		noelle:setSprite("battle/defeat")
		cutscene:wait(0.5)

		cutscene:text("* ...", "surprise_frown", "susie")
		cutscene:setAnimation(susie, {"away_scratch", 1/10, true})
		cutscene:text("* So, uh...", "neutral_side", "susie")
		cutscene:text("* Are you finished...?", "nervous_side", "susie")
		cutscene:text("* [speed:0.6]...Why...?", "trance", "noelle")
		cutscene:text("* Well... uh...", "nervous_side", "susie")
		cutscene:setSprite(susie, "exasperated_right")
		cutscene:text("* Hey, wait a sec!!")
		cutscene:text("* You're the one who attacked me first!")
		cutscene:text("* So I should be the one to ask!")
		cutscene:text("* WHY?!")
		cutscene:wait(1.5)
		cutscene:text("* ...", "trance", "noelle")
		cutscene:setSprite(noelle, "walk_sad")
		cutscene:text("* ...?")
		cutscene:text("* They are calling.")
		cutscene:text("* Calling...? Wh-")
		cutscene:walkTo(noelle, noelle.x+320, noelle.y, 5)
		local waitFade=cutscene:fadeOut(5)
		susie:shake(3)
		cutscene:text("* Hey! Noelle, where are you going?!", "surprise_frown", "susie")
		cutscene:text("* You just took an axe in your face and you just walk away??", "shy_b", "susie")
		cutscene:text("* Noelle! Answer, damnit!", "angry", "susie")
		cutscene:text("* Stop trying to go away!!", "angry_b", "susie")
		cutscene:text("* This isn't even the exit!!", "teeth_b", "susie")
		cutscene:text("* IT'S A FUCKING HEART-SHAPED FERRIS WHEEL!!!", "teeth", "susie")
		cutscene:wait(waitFade)
		cutscene:wait(1)
		cutscene:gotoCutscene("TEST_ENDING")
	end,
	killspare=function(cutscene)
		local susie = cutscene:getCharacter("susie")
		local noelle = cutscene:getCharacter("noelle")
		susie:setSprite("walk")
		cutscene:look(susie, "right")
		noelle:setSprite("battle/defeat")
		cutscene:wait(0.5)

		cutscene:text("* Noelle!", "surprise_frown", "susie")
		cutscene:text("* Can you hear me??", "sad_frown", "susie")
		cutscene:text("* [speed:0.6]...", "dejected", "noelle")
		cutscene:text("* [speed:0.4]...[wait:1]It hurts...", "sad", "noelle")
		noelle.actor.flip="left"
		noelle:setSprite("collapsed")
		Assets.playSound("noise")
		cutscene:text("* Noelle!", "surprise_frown", "susie")
		susie.actor.flip="right"
		cutscene:setAnimation(susie, {"spr_cutscene_18_susie_heal", 1/16})
		cutscene:wait(function()
			return susie.sprite.frame>=11
		end)
		Assets.playSound("snd_spellcast")
		local heal_bullet = Sprite('spr_cutscene_18_susie_heal_small', susie.x+susie.width, susie.y+susie.height/2)
		heal_bullet.layer=susie.layer+1
		Game.world:addChild(heal_bullet)
		heal_bullet:play(1/12, false)
		Game.world.timer:tween(2, heal_bullet, {x=noelle.x})
		cutscene:wait(2)
		heal_bullet:remove()
		local flash=FlashFade(noelle.sprite.texture, noelle.x, noelle.y)
        noelle.sprite:addChild(flash)
		Assets.playSound("snd_spell_cure_slight_smaller")
		cutscene:wait(0.45)
		local sus_layer=susie.layer
		susie.layer=0.3
		susie.actor.flip="left"
		susie:setSprite("walk")
		cutscene:wait(cutscene:walkTo(susie, noelle.x+noelle.width/2, noelle.y))
		cutscene:setSprite(susie, "landed")
		cutscene:wait(0.5)
		cutscene:text("* .[wait:1].[wait:1].[wait:1]", "bangs_neutral", "susie")
		cutscene:text("* She's still breathing...[wait:1] Good.", "bangs_neutral", "susie")
		susie:setSprite("walk")
		cutscene:look(susie, "down")
		cutscene:wait(0.75)
		cutscene:text("* ...[wait:1]What do I even do now?", "nervous", "susie")
		cutscene:wait(cutscene:walkTo(susie, 640, 287, 1, "up"))
		cutscene:wait(0.75)
		cutscene:look(susie, "right")
		cutscene:wait(0.5)
		cutscene:text("* ...", "neutral_side", "susie")
		cutscene:walkTo(susie, noelle.x+noelle.width/2, noelle.y, 1.5)
		cutscene:fadeOut(0.5)
		cutscene:wait(1)
		Assets.playSound("noise")
		cutscene:wait(1.5)
		Assets.playSound("snd_heavyswing_bc")
		susie.layer=sus_layer
		susie:setPosition(640, 287)
		cutscene:look(susie, "up")
		local noelle_head=Sprite("Noelle_sleeping_in_bed", 560, 185)
		noelle_head:setScale(2)
		noelle_head.layer=0.3
		Game.world:addChild(noelle_head)
		Game.world:getEvent(26):remove()
		cutscene:wait(0.25)
		cutscene:text("* (Susie took Noelle's ThornRing.)", nil, nil)
		cutscene:fadeIn(0.5)
		cutscene:wait(1)
		cutscene:text("* ...", "neutral_side", "susie")
		cutscene:text("* I better go check on Kris and Ralsei now.", "neutral", "susie")
		cutscene:look(susie, "left")
		cutscene:attachCamera(0.5)
		cutscene:wait(0.5)
	end,
	killkill=function(cutscene)
		cutscene:gotoCutscene("closing_fountain")
	end
}