return function(cutscene)
	local ending=Game:getFlag("noelle_battle_status", "killspare")
	local susie=cutscene:getCharacter("susie")
	local noelle=cutscene:getCharacter("noelle")

	cutscene:setTextboxTop(true)

	cutscene:text("* Wowowow!", "shock", "susie")
	cutscene:text("* What the hell?!", "angry_c", "susie")
	if ending=="no_trance" then
		noelle:setSprite("walk")
		cutscene:text("* Su-Susie...?! Are you okay??", "afraid", "noelle")
		cutscene:text("* Ah uhm...", "sad_frown", "susie")
		cutscene:text("* It's fine. Really.", "smirk", "susie")
		cutscene:text("* Just... moved faster than I expected. Haha.", "sincere_smile", "susie")
		cutscene:text("* Are you sure?", "sad_b", "noelle")
		cutscene:text("* Yeah! Don't worry about it.", "sincere", "susie")
		cutscene:text("* ...", "sad_b", "noelle")
		cutscene:text("* Alright then. I trust you.", "surprise_smile", "noelle")
	else
		cutscene:wait(1)
		cutscene:text("* (...)", "neutral_side", "susie")
	end

	cutscene:wait(1.5)
	local rect=Rectangle(0, 0, SCREEN_WIDTH+500, SCREEN_HEIGHT)
	rect:setColor(0,0,0,0)
    local sus_layer = susie:getLayer()
    susie:setLayer(WORLD_LAYERS["top"])
	Game.world:addChild(rect)
	rect:setLayer(WORLD_LAYERS["below_ui"])
	local fadein = Game.stage.timer:tween(2, rect, {alpha=1})
	susie:setSprite("walk_bangs")
	Game.world.music:play("mus_mysteriousroom2", nil, 0.8)
	cutscene:look(susie, "up")

	if ending=="no_trance" then
		cutscene:text("* [speed:0.7](\"moved faster than I expected\", yeah, almost that.)", nil, "susie")
		cutscene:text("* [speed:0.7](Something is [color:red]controlling[color:reset] me and I don't like that.)", nil, "susie")
		cutscene:text("* [speed:0.7](I thought it was only an impression when I was fighting Noelle)", nil, "susie")
		cutscene:text("* [speed:0.7](But something might be controlling me right now.)", nil, "susie")
		cutscene:text("* (...)", nil, "susie")
		cutscene:text("* (Well whatever.)", nil, "susie")
		cutscene:text("* (As long as they guide me and Noelle to Kris, I can do with it for the time being.)", nil, "susie")
		cutscene:wait(0.5)
		cutscene:look(susie, "down")
		cutscene:wait(0.5)
		cutscene:text("* (You heard me, you weird voice.)", "bangs_teeth", "susie")
	else
		cutscene:text("* [speed:0.7](So that's what's happening.)", nil, "susie")
		cutscene:text("* [speed:0.7](Something is [color:red]controlling[color:reset] me.)", nil, "susie")
		cutscene:text("* [speed:0.7](I was wondering why I drew my weapon against Noelle so ruthlessly)", nil, "susie")
		cutscene:text("* [speed:0.7](But now, I know why.)", nil, "susie")
		cutscene:text("* (...)", nil, "susie")
		cutscene:text("* (Well whatever.)", nil, "susie")
		cutscene:text("* (As long as they guide me to Kris, I'll overlook what was done.)", nil, "susie")
		cutscene:wait(0.5)
		cutscene:look(susie, "down")
		cutscene:wait(0.5)
		cutscene:text("* (You heard me, you creepy voice.)", "bangs_teeth", "susie")
	end

	Game.stage.timer:cancel(fadein)
	Game.stage.timer:tween(2, rect, {alpha=0}, nil, function() rect:remove() end)
	Game.world.music:fade(0, 2,function()
		Game.world.music:stop()
    	susie:setLayer(sus_layer)
	end)
	cutscene:wait(2.5)

	susie:setSprite("walk")
	cutscene:text("* Let's go.", ending=="no_trance" and "small_smile" or "bangs_smile", "susie")
end